
package io.github.mjhaugsdal.rest.types.utleverer;

import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.2
 * 2023-07-08T16:50:19.747+02:00
 * Generated source version: 4.0.2
 */

@WebFault(name = "AppRecFault", targetNamespace = "http://utleverer.webservices.reseptformidleren.ergo.no/")
@XmlRootElement
public class AppRecFault_Exception extends Exception {

    private AppRecFault faultInfo;

    public AppRecFault_Exception() {
        super();
    }

    public AppRecFault_Exception(String message) {
        super(message);
    }

    public AppRecFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AppRecFault_Exception(String message, AppRecFault appRecFault) {
        super(message);
        this.faultInfo = appRecFault;
    }

    public AppRecFault_Exception(String message, AppRecFault appRecFault, Throwable cause) {
        super(message, cause);
        this.faultInfo = appRecFault;
    }

    public AppRecFault getFaultInfo() {
        return this.faultInfo;
    }
}
