
package io.nettapotek.rest.hack.types;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-01-13T16:51:17.226+01:00
 * Generated source version: 3.5.5
 */

@WebFault(name = "AppRecFault", targetNamespace = "http://na.webservices.reseptformidleren.ergo.no/")
public class AppRecFault_Exception extends Exception {

    private AppRecFault faultInfo;

    public AppRecFault_Exception() {
        super();
    }

    public AppRecFault_Exception(String message) {
        super(message);
    }

    public AppRecFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AppRecFault_Exception(String message, AppRecFault appRecFault) {
        super(message);
        this.faultInfo = appRecFault;
    }

    public AppRecFault_Exception(String message, AppRecFault appRecFault, Throwable cause) {
        super(message, cause);
        this.faultInfo = appRecFault;
    }

    public AppRecFault getFaultInfo() {
        return this.faultInfo;
    }
}
